### ISSUE TITLE
specification of coordinates semantics

### ISSUE THREAD

**Issue by aflueckiger** [impresso/impresso-schemas#14]
@mromanello @ehoelzl 
We need to specify the semantics of the coordinates. Do they follow the IIIF [regions](https://iiif.io/api/image/2.0/#identifier) schema (x,y, w, h) or something else?

The current description is not precise enough.
`"description": "Coordinates of image-region.",`

**Comment by mromanello** [comment]
was it perhaps a case of non-converted coordinates? I've checked directly the code of some importers (Olive, Lux), and this is the semantic assumed by/implemented in the code.

**Comment by simon-clematide** [comment]
@mromanello @ehoelzl  Yes, you are right. https://github.com/impresso/impresso-schemas/blob/master/examples/newspaper_page/example0.json has cc="False". 
So the semantics of the coordinates is x,y,width,height if cc="True".
Otherwise, it is probably x1,y1,x2,y2 .
I would rather want the "c" attribute to be reserved for correct IIIF conformant coordinates (or null if they are not available). Original unconverted coordinates at the same place are very irritating.
I would rather ban them in a separate "c_orig" if we want to keep them around. But nobody should interpret them as "normal" coordinates.

**Comment by mromanello** [comment]
in principle you are right. In practice hesitate a bit to say "yes, let's go for that" as this would trigger a complete re-ingestion of all our canonical data...

**Comment by simon-clematide** [comment]
agreed.. but if we completely re-ingest we should change it. It will for sure bite us again in the future, otherwise.
